### ISSUE TITLE
Error creating service-linked role with name ecs.amazonaws.com

### ISSUE THREAD

**Issue by rjjaegeraws** [bcgov/startup-sample-project#13]
Creating the AWSServiceRoleForECS in Terraform may be problematic if it already exists. Also, if there are other applications running on ECS in the same AWS Account, deleting it as part of a Terraform destroy could impact other deployments. 

I recommend moving this outside of Terraform and into the makefile.

If you run the deploy with this service-linked role already created, it fails with the following message: 

InvalidInput: Service role name AWSServiceRoleForECS has been taken in this account, please try a different suffix.

`
  on terraform/aws/ecs.tf line 3, in resource "aws_iam_service_linked_role" "service-linked-role":
   3: resource "aws_iam_service_linked_role" "service-linked-role" {
`

**Comment by sheaphillips** [comment]
Agreed. Now that I understand how the linked role relates, I can see that it would be difficult/inappropriate to manage in TF.  If it's explicitly needed for ECS provisioning, we may be able to drop in a TF `data` element pointing to the linked role so it will fail if it doesn't already exist.

**Comment by sheaphillips** [comment]
As a workaround, running tf a second time worked for me. I think there is a race condition due to parallelism and a missing `depends_on` somewhere...
